[workspace]
resolver = "3"
members = [
    "crates/asdf-core",
    "crates/asdf-yaml",
    "crates/libasdf-rs",
    "crates/asdf",
    "crates/asdf-cli",
]

[workspace.package]
version = "0.1.2"
edition = "2024"
rust-version = "1.90"
license = "MIT"
repository = "https://github.com/cruzzil/asdf"
authors = ["The libasdf-rs Developers"]

[workspace.dependencies]
asdf-core = { path = "crates/asdf-core", version = "0.1.2" }
asdf-yaml = { path = "crates/asdf-yaml", version = "0.1.2" }

saphyr-parser = "0.0.12"
thiserror = "2"
hashlink = "0.10"
half = "2"
libc = "0.2"
md-5 = "0.10"
flate2 = "1"
bzip2 = "0.6"
lz4_flex = "0.11"
memmap2 = "0.9"

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "deny"
missing_debug_implementations = "warn"

[profile.release]
lto = "thin"
