[package]
name = "asdf-yaml"
description = "ASDF-flavoured YAML document model, parser and emitter"
version = "0.1.2"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
saphyr-parser.workspace = true
hashlink.workspace = true
thiserror.workspace = true

[lints]
workspace = true
