[package]
name = "asdf-rs"
description = "Idiomatic Rust API for the ASDF (Advanced Scientific Data Format) file format"
version = "0.1.2"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lib]
name = "asdf"
path = "src/lib.rs"

[dependencies]
asdf-core.workspace = true

[lints]
workspace = true

[dev-dependencies]
divan = "0.1.21"

[[bench]]
name = "throughput"
harness = false
